In [ ]:
!pip install tensorflow

In [ ]:
# importing the tensorflow module
import tensorflow as tf

In [ ]:
# check the tensorflow version
print(tf.__version__)

2.15.0


### Some Examples Of TensorFlow **tensors**

In [ ]:
# regular variables.
text = tf.Variable("Learning TensorFlow", tf.string)
integer = tf.Variable(100000, tf.int16)
decimal = tf.Variable(12.345, tf.float64)

In [ ]:
# 1-dimensional tensor
tensor_1d = tf.Variable([1, 2, 3, 4, 5], tf.int32)

In [ ]:
# 2-dimensional vector
tensor_2d = tf.Variable([[1, 2, 3], [4, 5, 6]], tf.int32)

In [ ]:
# determine the rank of the 1d and 2d vectors
# defined in the previous cells.
print(tf.rank(tensor_1d))
print(tf.rank(tensor_2d))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# print the shape of each tensor
# which we created in earlier cells
print(tensor_1d.shape)
print(tensor_2d.shape)

(5,)
(2, 3)


In [ ]:
# example of how to change
# the shape of a tensor
tensor_2d = tf.reshape(tensor_2d, [3, 2])
print(tensor_2d)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
# matrix with 5 rows
# and 5 columns containing
# decimal numbers
matrix_5x5 = tf.Variable(tf.random.uniform([5, 5], 0, 1))
print(matrix_5x5)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[0.4790815 , 0.558849  , 0.26568604, 0.8936378 , 0.79865   ],
       [0.68829155, 0.31673968, 0.9043186 , 0.16667676, 0.28446352],
       [0.43490648, 0.6998658 , 0.65408254, 0.42688847, 0.97053814],
       [0.38188362, 0.16170537, 0.4051335 , 0.01381969, 0.86928904],
       [0.08335936, 0.8987994 , 0.644091  , 0.25638652, 0.72783506]],
      dtype=float32)>


In [ ]:
# print the 3rd element
# of 2nd row of the last
# tensor
print(matrix_5x5[1, 2])

tf.Tensor(0.9043186, shape=(), dtype=float32)


In [ ]:
# print the 5th element
# of the 3rd row
print(matrix_5x5[2, 4])

tf.Tensor(0.97053814, shape=(), dtype=float32)


In [ ]:
# select 1st and 4th row
# of the last tensor
print(matrix_5x5[0:2, :])

tf.Tensor(
[[0.4790815  0.558849   0.26568604 0.8936378  0.79865   ]
 [0.68829155 0.31673968 0.9043186  0.16667676 0.28446352]], shape=(2, 5), dtype=float32)
